# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  BuildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: build
    configuration: '$(BuildConfiguration)'
    
- task: DotNetCoreCLI@2
  inputs:
    command: test
    configuration: '$(BuildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    packagesToPack: 'Trine.Analyzer/Trine.Analyzer.csproj'
    versioningScheme: 'byBuildNumber'
    configurationToPack: '$(BuildConfiguration)'

